version: '3.8'

services:

  redis:
      image: redis:latest
      container_name: redis
      ports:
        - "6379:6379"
      command: ["redis-server", "--appendonly", "yes"]
      volumes:
        - redis:/var/lib/redis/data

  redis-commander:
    image: rediscommander/redis-commander:latest
    container_name: redis-ui
    environment:
      REDIS_HOSTS: "local:redis:6379"
      HTTP_USER: "zxc"
      HTTP_PASSWORD: "zxc"
    ports:
      - "8081:8081"
    depends_on:
      - redis

volumes:
  redis: